[project]
name = "pyformatter"
version = "0.1.0"
dependencies = []
requires-python = ">=3.11"

[project.scripts]
pydocfmt = "pyformatter.cli.pydocfmt_main:main"
pycommentfmt = "pyformatter.cli.pycommentfmt_main:main"